spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/sporttrack
#      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME}
      database: sporttrack
auth:
  jwt:
    expirationDays: 30
    secret: secret123
    issuer: sporttrack-backend
server:
  port: 8000

cors:
  origins: "http://ec2***********************************************:3000,http://localhost:3000"

